# Generated by Django 6.0.4 on 2026-06-01 15:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import http
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=4)),
                ('expected_status_code', models.PositiveSmallIntegerField(choices=[(100, '100 Continue'), (101, '101 Switching Protocols'), (102, '102 Processing'), (103, '103 Early Hints'), (200, '200 OK'), (201, '201 Created'), (202, '202 Accepted'), (203, '203 Non-Authoritative Information'), (204, '204 No Content'), (205, '205 Reset Content'), (206, '206 Partial Content'), (207, '207 Multi-Status'), (208, '208 Already Reported'), (226, '226 IM Used'), (300, '300 Multiple Choices'), (301, '301 Moved Permanently'), (302, '302 Found'), (303, '303 See Other'), (304, '304 Not Modified'), (305, '305 Use Proxy'), (307, '307 Temporary Redirect'), (308, '308 Permanent Redirect'), (400, '400 Bad Request'), (401, '401 Unauthorized'), (402, '402 Payment Required'), (403, '403 Forbidden'), (404, '404 Not Found'), (405, '405 Method Not Allowed'), (406, '406 Not Acceptable'), (407, '407 Proxy Authentication Required'), (408, '408 Request Timeout'), (409, '409 Conflict'), (410, '410 Gone'), (411, '411 Length Required'), (412, '412 Precondition Failed'), (413, '413 Content Too Large'), (414, '414 URI Too Long'), (415, '415 Unsupported Media Type'), (416, '416 Range Not Satisfiable'), (417, '417 Expectation Failed'), (418, "418 I'm a Teapot"), (421, '421 Misdirected Request'), (422, '422 Unprocessable Content'), (423, '423 Locked'), (424, '424 Failed Dependency'), (425, '425 Too Early'), (426, '426 Upgrade Required'), (428, '428 Precondition Required'), (429, '429 Too Many Requests'), (431, '431 Request Header Fields Too Large'), (451, '451 Unavailable For Legal Reasons'), (500, '500 Internal Server Error'), (501, '501 Not Implemented'), (502, '502 Bad Gateway'), (503, '503 Service Unavailable'), (504, '504 Gateway Timeout'), (505, '505 HTTP Version Not Supported'), (506, '506 Variant Also Negotiates'), (507, '507 Insufficient Storage'), (508, '508 Loop Detected'), (510, '510 Not Extended'), (511, '511 Network Authentication Required')], default=http.HTTPStatus['OK'])),
                ('check_interval_seconds', models.PositiveSmallIntegerField(default=600, validators=[django.core.validators.MinValueValidator(20)])),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_up', models.BooleanField()),
                ('status_code', models.PositiveSmallIntegerField(blank=True, choices=[(100, '100 Continue'), (101, '101 Switching Protocols'), (102, '102 Processing'), (103, '103 Early Hints'), (200, '200 OK'), (201, '201 Created'), (202, '202 Accepted'), (203, '203 Non-Authoritative Information'), (204, '204 No Content'), (205, '205 Reset Content'), (206, '206 Partial Content'), (207, '207 Multi-Status'), (208, '208 Already Reported'), (226, '226 IM Used'), (300, '300 Multiple Choices'), (301, '301 Moved Permanently'), (302, '302 Found'), (303, '303 See Other'), (304, '304 Not Modified'), (305, '305 Use Proxy'), (307, '307 Temporary Redirect'), (308, '308 Permanent Redirect'), (400, '400 Bad Request'), (401, '401 Unauthorized'), (402, '402 Payment Required'), (403, '403 Forbidden'), (404, '404 Not Found'), (405, '405 Method Not Allowed'), (406, '406 Not Acceptable'), (407, '407 Proxy Authentication Required'), (408, '408 Request Timeout'), (409, '409 Conflict'), (410, '410 Gone'), (411, '411 Length Required'), (412, '412 Precondition Failed'), (413, '413 Content Too Large'), (414, '414 URI Too Long'), (415, '415 Unsupported Media Type'), (416, '416 Range Not Satisfiable'), (417, '417 Expectation Failed'), (418, "418 I'm a Teapot"), (421, '421 Misdirected Request'), (422, '422 Unprocessable Content'), (423, '423 Locked'), (424, '424 Failed Dependency'), (425, '425 Too Early'), (426, '426 Upgrade Required'), (428, '428 Precondition Required'), (429, '429 Too Many Requests'), (431, '431 Request Header Fields Too Large'), (451, '451 Unavailable For Legal Reasons'), (500, '500 Internal Server Error'), (501, '501 Not Implemented'), (502, '502 Bad Gateway'), (503, '503 Service Unavailable'), (504, '504 Gateway Timeout'), (505, '505 HTTP Version Not Supported'), (506, '506 Variant Also Negotiates'), (507, '507 Insufficient Storage'), (508, '508 Loop Detected'), (510, '510 Not Extended'), (511, '511 Network Authentication Required')], null=True)),
                ('response_time_ms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=200, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.monitor')),
            ],
        ),
    ]
