# Generated by Django 6.0.4 on 2026-05-09 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_alter_checkresult_checked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='check_interval_seconds',
            field=models.PositiveSmallIntegerField(default=600, validators=[django.core.validators.MinValueValidator(20)]),
        ),
    ]
