# Generated by Django 6.0.4 on 2026-05-01 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='check_interval_seconds',
            field=models.PositiveSmallIntegerField(default=600, validators=[django.core.validators.MinValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='timeout_seconds',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
