# Generated by Django 6.0.4 on 2026-05-02 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_alter_monitor_check_interval_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkresult',
            name='checked_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
